---
title: Secure Medicine
timezone: UTC
collections:
  events:
    title: Events
    output: true
    values:
      layout: event
  members:
    title: Members
    output: false
  posts:
    title: Posts
    output: true
  publications:
    title: Publications
    output: true
  speakers:
    title: Speakers
    output: true
  team:
    title: Team
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    banner_text: Add a banner title
    layout: page
- scope:
    path: ''
    type: posts
  values:
    layout: post
    leadin_text: ''
    photo: ''
    author: ''
- scope:
    path: ''
    type: events
  values:
    subtitle: ''
    start_date: 2016-09-01 21:45:00.000000000 Z
    end_date: 2016-09-05 21:45:00.000000000 Z
    location: ''
    layout: event
- scope:
    path: publications
    type: publications
  values:
    layout: event
- scope:
    path: ''
    type: members
  values:
    website: ''
    logo_image: ''
    social:
    - twitter_username: ''
    - facebook: ''
    - youtube_channel: ''
    - linkedin_username: ''
gems:
- bootstrap
email: info@secure-medicine.org
description: 'A cross-disciplinary research initiative on medical device security,
  privacy, safety, and effectiveness

'
baseurl: 
url: https://secure-medicine.org
twitter_username: ARC_MedSec
github_username: Jonesy
linkedin_username: https://www.linkedin.com/groups/12031242
youtube_channel: https://www.youtube.com/user/michiganengineering
markdown: kramdown
kramdown:
  input: GFM
banner_image: "/uploads/01Home_Main_Image.jpg"
social:
- twitter_username: ARC_MedSec
- youtube_channel: https://www.youtube.com/user/michiganengineering
- linkedin_username: https://www.linkedin.com/groups/12031242
