---
title: Secure Medicine
timezone: UTC
collections:
  events:
    title: Events
    output: true
    start_date: "2016-08-02 00:00:00.000000000 Z"
    end_date: "2016-08-02 00:00:00.000000000 Z"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
  scope:
    type: "events"
    path: "events"
  values:
    start_date: "2016-07-21 09:30:00 Z"
    end_date: "2016-07-21 09:30:00 Z"
    layout: "event"
gems:
- bootstrap
email: joshua@general-metrics.com
description: |
  A cross-disciplinary research initiative on medical device security, privacy, safety, and effectiveness
baseurl:
url: https://secure-medicine.org
twitter_username: ARC_MedSec
github_username: Jonesy
markdown: kramdown
