---
title: Secure Medicine
timezone: UTC
collections:
  events:
    title: Events
    output: true
    values:
      layout: event
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
  - scope:
      path: "events"
      type: events
    values:
      layout: event
gems:
- bootstrap
email: joshua@general-metrics.com
description: |
  A cross-disciplinary research initiative on medical device security, privacy, safety, and effectiveness
baseurl:
url: https://secure-medicine.org
twitter_username: ARC_MedSec
github_username: Jonesy
markdown: kramdown
