---
title: Secure Medicine
timezone: UTC
collections:
  events:
    title: Events
    output: true
    values:
      layout: event
  posts:
    title: Posts
    output: true
  publication:
    title: Publication
    output: true
    permalink: publications
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ""
    type: "events"
  values:
    start_date: 2016-09-01 21:45:00 Z
    end_date: 2016-09-05 21:45:00 Z
    layout: event
- scope:
    path: publications
    type: publication
  values:
    layout: event
gems:
- bootstrap
email: joshua@general-metrics.com
description: |
  A cross-disciplinary research initiative on medical device security, privacy, safety, and effectiveness
baseurl:
url: https://secure-medicine.org
twitter_username: ARC_MedSec
github_username: Jonesy
markdown: kramdown
